#
# file encoding: MUST UTF-8
#

# 민감상병

# 성매개감염병
SDZ_SEXUAL_KCD: &sdz_sexual_kcd "\\b(?-i:\
    (A5[0-7]|A6[05]|A7[04])(\\.?\\d{,3})?\
    |A63\\.?0\\d{,2}\
    |J98\\.?0\\d{,2}\
    |J16\\.?0\\d{,2}\
    |K67\\.?[012]\\d{,2}\
    |M03\\.?1\\d{,2}\
    |M73\\.?[01]\\d{,2}\
    |N29\\.?0\\d{,2}\
    |N74\\.?[234]\\d{,2}\
    |O98\\.?[12]\\d{,2}\
    |P23\\.?1\\d{,2}\
    |R76\\.?2\\d{,2}\
    )\\b"


# 후천성면역결핍증
SDZ_AIDS_KCD: &sdz_aids_kcd "\\b(?-i:\
    (B2[0-4]|R75|Z21)(\\.?\\d{,3})?\
    |(O98\\.?7|Z11\\.?4|Z20\\.?6|Z71\\.?7|Z83\\.?0)\\d{,2}\
    )\\b"


# 학대
SDZ_ABUSE_KCD: &sdz_abuse_kcd "\\b(?-i:(T74|Y0[57])(\\.?\\d{,3})?)\\b"


# 낙태
SDZ_ABORTION_KCD: &sdz_abortion_kcd "\\b(?-i:O0[47](\\.?\\d{,3})?)\\b"

# 정신질환
SDZ_MENTAL_KCD: &sdz_mental_kcd "\\b(?-i:F\\d{2}(\\.?\\d{,3})?)\\b"


# 희귀질환
SDZ_RARE_KCD: &sdz_rare_kcd "\\b(?-i:\
    (A31\\.?9|A81\\.?0)\\d{,2}\
    |(D6[67]|D7[01])\\.?\\d{,3}\
    |(D12\\.?6|D55\\.?[02]|D56\\.?[0-4]|D59\\.?[35]|D60\\.?0|D61\\.?[039]|D64\\.?4|D68\\.?[01256]|D69\\.?[134])\\d{,2}\
    |(D76\\.?[13]|D80\\.?[0-68]|D81\\.?[0-9]|D82\\.?[0-4]|D83\\.?[012]|D84\\.?[01]|D86\\.?[0-38]|D89\\.?1)\\d{,2}\
    |(E16\\.?10)\\d{,1}\
    |(E20\\.?1|E2[23]\\.?0|E24\\.?[013]|E25\\.[09]|E26\\.?8|E27\\.?[124]|E34\\.?8|E55\\.?0)\\d{,2}\
    |(E70\\.?[0-38]|E71\\.?[013]|E72\\.?[0-58]|E73\\.?0|E74\\.?[0248]|E75\\.?[01245]|E76\\.?[012]|E77\\.?[01])\\d{,2}\
    |(E79\\.?1|E80\\.?2|E83\\.?[0-3]|E84\\.?[01]|E85\\.?[0124]|E88\\.?[01])\\d{,2}\
    |(F01\\.?1|F80\\.?3|F84\\.?2)\\d{,2}\
    |(G10|G35)\\.?\\d{,3}\
    |(G31\\.?8[18]|G47\\.?31)\\d{,1}\
    |(G04\\.?8|G11\\.?[0-489]|G12\\.?[01289]|G23\\.?[018]|G2[45]\\.?8|G36\\.?0|G40\\.?4|G41\\.?[01289])\\d{,2}\
    |(G47\\.?4|G51\\.?[28]|G60\\.?0|G61\\.?8|G70\\.?[02]|G71\\.?[0-39]|G72\\.?[34]|G73\\.?1|G90\\.?[56]|G93\\.?4|G95\\.?0)\\d{,2}\
    |(H16\\.?3|H18\\.?[56]|H31\\.?2|H35\\.?0|H49\\.?[48]|H51\\.?8)\\d{,2}\
    |(H35\\.?5[1289])\\d{,1}\
    |(I27\\.?[08]|I42\\.?[0134]|I47\\.?2|I67\\.?5|I73\\.?1|I78\\.?0|I82\\.?0)\\d{,2}\
    |(I42\\.?20|I42\\.?80|I49\\.?82)\\d{,1}\
    |(J39\\.?8|J84\\.?[01])\\d{,2}\
    |(K00\\.?51)\\d{,1}\
    |(K50\\.?[018]|K74\\.?3|K75\\.?4|K83\\.?0)\\d{,2}\
    |(L73\\.?22)\\d{,1}\
    |(L10\\.?[02]|L12\\.?[013])\\d{,2}\
    |(M06\\.?1|M08\\.?[0-3]|M30\\.?[012]|M31\\.?[01347]|M32\\.?1|M33\\.?[012]|M34\\.?[018]|M35\\.?[0-6])\\d{,2}\
    |(M61\\.?1|M88\\.?[089]|M92\\.?2|M9[34]\\.?1)\\d{,2}\
    |(N04\\.?[0-7]|N25\\.?1)\\d{,2}\
    |(P35\\.?[04])\\d{,2}\
    |(Q03\\.?1|Q04\\.?[236]|Q05\\.?[0-9]|Q06\\.?2|Q07\\.?0|Q11\\.?2|Q13\\.?[18]|Q14\\.?[12]|Q16\\.?1|Q17\\.?2)\\d{,2}\
    |(Q20\\.?[0-6]|Q21\\.?[2348]|Q22\\.?[0456]|Q23\\.?[0-489]|Q24\\.?[456]|Q25\\.?[1235]|Q26\\.?[0-6]|Q28\\.?2)\\d{,2}\
    |(Q38\\.?3|Q43\\.?8|Q44\\.?[267]|Q61\\.?[19]|Q64\\.?1|Q74\\.?[038]|Q75\\.?[014]|Q76\\.?1|Q77\\.?[0-9])\\d{,2}\
    |(Q78\\.?[0-69]|Q79\\.?[0-689]|Q80\\.?[1-4]|Q81\\.?[012]|Q82\\.?[0348]|Q85\\.?[018]|Q86\\.?0|Q87\\.?[0-58])\\d{,2}\
    |(Q90\\.?[0129]|Q91\\.?[0124-7]|Q92\\.?[238]|Q93\\.?[2-5]|Q96\\.?[0-4]|Q98\\.?[012]|Q99\\.?[28])\\d{,2}\
    )"
